[package]
name = "aeron-rust-wrapper"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
aeron-rs = { path = "../aeron-rs" }

[build-dependencies]
cxx-build = "1.0"